# Generated by Django 5.0.7 on 2024-10-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_spotifytoken_youtubetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
