# Generated by Django 5.0.7 on 2024-11-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_alter_spotifytoken_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubetoken',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='youtubetoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
