# Generated by Django 5.0.7 on 2024-11-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_rename_playlist_spotify_playlist_youtube_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotify_playlist',
            name='image_url',
            field=models.URLField(default='/static/playlist/noimage.jpg'),
        ),
        migrations.AddField(
            model_name='spotify_playlist',
            name='spotify_playlist_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='youtube_playlist',
            name='image_url',
            field=models.URLField(default='/static/playlist/noimage.jpg'),
        ),
        migrations.AddField(
            model_name='youtube_playlist',
            name='youtube_playlist_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
